# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"return_base_path_deduplicated": "00_core.ipynb",
         "check_uniques": "00_core.ipynb",
         "drop_duplicates": "00_core.ipynb",
         "get_id": "00_core.ipynb",
         "split_w_stratify": "00_core.ipynb",
         "train_valid_split_w_stratify": "00_core.ipynb",
         "prepare_dataset": "00_core.ipynb",
         "prepare_transforms": "00_core.ipynb",
         "FlyswotData": "00_core.ipynb",
         "prep_data": "00_core.ipynb",
         "collate_fn": "00_core.ipynb",
         "train_model": "00_core.ipynb",
         "plot_confusion_matrix": "00_core.ipynb",
         "create_classification_report": "00_core.ipynb",
         "create_misclassified_report": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://davanstrien.github.io/flyswot_gym/"

git_url = "https://github.com/davanstrien/flyswot_gym/tree/master/"

def custom_doc_links(name): return None
